### ISSUE TITLE
Make Add-on SDK (Jetpack) work on Pale Moon

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#120]
This is the Meta bug for making `Add-on SDK` (Jetpack) work on `Pale Moon`.

---

- [x] Add `Pale Moon` as a target engine to `sdk/system/xul-app.jsm`
- [x] Add `Pale Moon` to `modules/system/Startup.js` (bugs [851426](https://bugzilla.mozilla.org/show_bug.cgi?id=851426) and [1042239](https://bugzilla.mozilla.org/show_bug.cgi?id=1042239))
- [x] Update `module.metadata` with the `Pale Moon` engine where appropriate in `sdk/*`
- [x] Add the `PMkit` shim for `sdk/ui/button` ([PM27#808](https://github.com/MoonchildProductions/Pale-Moon/pull/808), [PM27#818](https://github.com/MoonchildProductions/Pale-Moon/pull/818), [PM27#918](https://github.com/MoonchildProductions/Pale-Moon/pull/918))
- [x] Allow access to `sdk/ui/buttons` via `require('sdk/ui')` ([PM27#811](https://github.com/MoonchildProductions/Pale-Moon/pull/811))
- [x] Deal with `sdk/tabs`
  - [x] ~Fix memory leak ([PM27#776](https://github.com/MoonchildProductions/Pale-Moon/pull/776))~ already fixed in UXP
  - [x] ~Investigate the possibility to de-e10s ([PM27#785](https://github.com/MoonchildProductions/Pale-Moon/pull/785))~ see #331
- [x] Deal with `sdk/context-menu` and `sdk/context-menu@2`
  - [x] Provide gContextMenuContentData ~([PM27#778](https://github.com/MoonchildProductions/Pale-Moon/pull/778), [PM27#780](https://github.com/MoonchildProductions/Pale-Moon/pull/780))~ (steal from Basilisk)
  - [x] ~Fix TypeError in messageManager ([PM27#783](https://github.com/MoonchildProductions/Pale-Moon/pull/783))~ already fixed in UXP
  - [x] ~Investigate the possibility to de-e10s ([PM27#784](https://github.com/MoonchildProductions/Pale-Moon/pull/784))~ see #331
  - [x] ~Remove `sdk/context-menu@2` ([PM27#787](https://github.com/MoonchildProductions/Pale-Moon/pull/787))~ see #331
- [x] Remove embedded WebExtensions support (bug [1269347](https://bugzilla.mozilla.org/show_bug.cgi?id=1269347))
- [x] ~Investigate the possibility to revive `sdk/widget` ([PM27#777](https://github.com/MoonchildProductions/Pale-Moon/pull/777), [PM27#781](https://github.com/MoonchildProductions/Pale-Moon/pull/781))~ consider impractical, `sdk/ui/button` is just enough
- [x] Verify all `PMkit` adapted add-ons from the [pm27-sdk-addons](https://github.com/JustOff/pm27-sdk-addons) list work properly
- [x] Fix `Empty string passed to getElementById()` warning in `buttons.js`

Blocks #57

**Comment by mattatobin** [comment]
Remember what ever you do cannot bust an jetpack extension on Basilisk.. When in doubt.. Preprocess and mozbuild conditional.

**Comment by JustOff** [comment]
> Preprocess and mozbuild conditional.

I need your help with this. How, for example, can I specify that I need to preprocess `toolkit/jetpack/sdk/ui/button/view.js ` and pack `toolkit/jetpack/sdk/ui/buttons.js` only when `MC_PALEMOON=1`?

**Comment by mattatobin** [comment]
https://github.com/MoonchildProductions/UXP/commit/8f6d3dab81c7f8f97ef197e26ab9439b09735b8f

Pretty much like that to preprocess..

**Comment by JustOff** [comment]
Thanks, looks like now I handled it.

Btw, how about [don't generate Line/File/Directory comments in preprocessed files](https://github.com/MoonchildProductions/Pale-Moon/commit/4b644c3cd1d1c1881a3ea8f5f895e6ce599eb716) as it was done for Tycho?

**Comment by mattatobin** [comment]
Is that causing an issue.. Personally, i don't have a problem with it..

**Comment by mattatobin** [comment]
Push up a branch and link it I will take a gander @Justoff

**Comment by JustOff** [comment]
> Is that causing an issue.. Personally, i don't have a problem with it..

There is no big issue, but is there any benefit in such comments? 
IMHO this just makes the code almost unreadable, for example:
```
//@line 163 "d:\UXP\toolkit\jetpack\sdk\ui\button\view.js"
      node.setAttribute('id', _id);
//@line 167 "d:\UXP\toolkit\jetpack\sdk\ui\button\view.js"
      node.setAttribute('class', 'toolbarbutton-1 chromeclass-toolbar-additional badged-button');
//@line 171 "d:\UXP\toolkit\jetpack\sdk\ui\button\view.js"
      node.setAttribute('label', label);
      node.setAttribute('tooltiptext', label);
      node.setAttribute('image', image);
//@line 175 "d:\UXP\toolkit\jetpack\sdk\ui\button\view.js"
      node.setAttribute('pmkit-button', 'true');
//@line 179 "d:\UXP\toolkit\jetpack\sdk\ui\button\view.js"

      views.set(id, {
//@line 184 "d:\UXP\toolkit\jetpack\sdk\ui\button\view.js"
        icon: icon,
        label: label
      });
```

> Push up a branch and link it

I expect this to be done in a few minutes, I do the final checks right now.

**Comment by mattatobin** [comment]
The idea is that very large files like browser.js can be hard to relate between raw source and the final processed version.

**Comment by mattatobin** [comment]
Blocks #57

**Comment by JustOff** [comment]
I've moved all non-blocking issues to #331, so this task can be considered complete once #330 is merged.

**Comment by mattatobin** [comment]
Sounds good.. You are doing a good job man!

**Comment by JustOff** [comment]
Thanks, well, now this is no longer blocking #57.
