### ISSUE TITLE
Front-end issues with Pale Moon application

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#121]
A collection of front-end issues with the Pale Moon application on UXP.

- [x] Browser console: source links to chrome:// URIs load content page instead
- [x] `nsFaviconService::setAndFetchFaviconForPage()` deprecated, please use `nsFaviconService::setAndFetchFaviconForPage(..., [optional aLoadingPrincipal])` tabbrowser.xml:776:14
- [x] `nsIOService::NewChannelFromURI()` deprecated, please use `nsIOService::NewChannelFromURI2()` WindowsPreviewPerTab.jsm:77:16
- [x] `nsICookieManager2.getCookiesFromHost()` is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2 SessionStore.jsm:2405:17
- [x] Warning: Property contained reference to invalid variable.  Error in parsing value for ‘background-color’.  Falling back to ‘initial’.
Source File: chrome://devtools/skin/webconsole.css
Line: 406, Column: 9402
Source Code:
` var(--theme-tab-toolbar-background)`
- [x] Warning: Property contained reference to invalid variable.  Error in parsing value for ‘border-top-width’.  Falling back to ‘initial’.
Source File: chrome://devtools/skin/webconsole.css
Line: 407, Column: 9459
Source Code:
` 1px solid var(--theme-splitter-color)`
- [x] Warning: Property contained reference to invalid variable.  Error in parsing value for ‘border-top-width’.  Falling back to ‘initial’.
Source File: chrome://devtools/skin/widgets.css
Line: 84, Column: 2850
Source Code:
` var(--devtools-splitter-top-width)`
- [x] Warning: Property contained reference to invalid variable.  Error in parsing value for ‘border-bottom-width’.  Falling back to ‘initial’.
Source File: chrome://devtools/skin/widgets.css
Line: 85, Column: 2908
Source Code:
` var(--devtools-splitter-bottom-width)`
- [x] Places: Error: SyntaxError: non-generator method definitions may not contain yield
Source File: resource:///modules/MigrationUtils.jsm
Line: 510, Column: 8
Source Code:
`        yield migrator; `
- [x] Places: Error: ReferenceError: can't access lexical declaration `ContentArea' before initialization
Source File: chrome://browser/content/places/downloadsViewOverlay.xul
Line: 21
- [x] Places: Error: TypeError: PlacesOrganizer is undefined
Source File: chrome://browser/content/places/places.xul
Line: 1
- [x] Error: DEPRECATION WARNING: getURLAndPostDataForKeyword() is deprecated, please use PlacesUtils.keywords.fetch() instead
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=1100294
resource://gre/modules/PlacesUtils.jsm 1225 getURLAndPostDataForKeyword
chrome://browser/content/browser.js 8508 getShortcutOrURI
chrome://browser/content/urlbarBindings.xml 401 _canonizeURL
chrome://browser/content/urlbarBindings.xml 277 handleCommand
chrome://global/content/bindings/autocomplete.xml line 458 > Function 1 anonymous
chrome://global/content/bindings/autocomplete.xml 272 onTextEntered
chrome://global/content/bindings/autocomplete.xml 575 handleEnter
chrome://global/content/bindings/autocomplete.xml 538 handleKeyPress
chrome://global/content/bindings/autocomplete.xml 470 onKeyPress
chrome://global/content/bindings/autocomplete.xml 652 onxblkeypress
Source File: resource://gre/modules/Deprecated.jsm
Line: 79
- [x] Tabs do not have a border.
- [x] short-hand declarations for `Components.*` (Ci, Cu, etc.) redeclaration errors.
- [x] Tearing off tabs is broken.
- [x] Permissions manager and permissions dialogs are broken.

**Comment by mattatobin** [comment]
Blocks #57

**Comment by JustOff** [comment]
> Error: DEPRECATION WARNING: `getURLAndPostDataForKeyword()` is deprecated, please use `PlacesUtils.keywords.fetch()` instead

Since `PlacesUtils.getURLAndPostDataForKeyword()` is [used only once in browser.js](https://github.com/MoonchildProductions/UXP/blob/60c526db500f4f0d177cd7467c0b40bc2a205c1d/application/palemoon/base/content/browser.js##L1924-L1925), is there a reason to [rewrite it using Promises](https://bugzilla.mozilla.org/show_bug.cgi?id=1100294)? What if we will simply [un-deprecate it](https://github.com/MoonchildProductions/UXP/blob/eda34d02aa8159def0d811846e9417c37cea15cd/toolkit/components/places/PlacesUtils.jsm###L1222-#L1227)?

**Comment by janekptacijarabaci** [comment]
...also files are not uploaded when drag and drop (to the browser area) is used:
```
Error: TypeError: aKeyword.toLowerCase is not a function
Source File: resource://gre/modules/PlacesUtils.jsm
Line: 1234
```

**Comment by mattatobin** [comment]
Given that.. I suppose we should use the promise implementation..

**Comment by wolfbeast** [comment]
As a general rule, we'll want to adapt the front-end to the back-end here.

**Comment by janekptacijarabaci** [comment]
```
Error: DEPRECATION WARNING: getURLAndPostDataForKeyword() is deprecated,
please use PlacesUtils.keywords.fetch() instead
```

and

Files are not uploaded when drag and drop (to the browser area) is used:
```
Error: TypeError: aKeyword.toLowerCase is not a function
Source File: resource://gre/modules/PlacesUtils.jsm
Line: 1234
```

A test branch e.g.:
[tree@pm_url_1](https://github.com/janekptacijarabaci/UXP/tree/pm_url_1)

__Implemented:__
[Bug 846635](https://hg.mozilla.org/mozilla-central/rev/19845a51b863) Use asynchronous getCharsetForURI in getShortcutOrURI
[Bug 989984](https://hg.mozilla.org/mozilla-central/rev/336c25e3063e) getShortcutOrURIAndPostData should have a synchronous callback behavior
[Bug 1100291](https://hg.mozilla.org/mozilla-central/rev/5727e5db4bb1) Make getShortcutOrURIAndPostData() async by calling the passed callback off a zero timeout
[Bug 1100294](https://hg.mozilla.org/mozilla-central/rev/5541383f6c41) Turn getShortcutOrURIAndPostData() into a task that uses the new keywords API
[Bug 92737](https://bugzilla.mozilla.org/show_bug.cgi?id=92737) DnD of multiple shortcuts from desktop only opens one

**Comment by wolfbeast** [comment]
Borders fixed with reinstating natural border width rounding.

**Comment by JustOff** [comment]
`Error: DEPRECATION WARNING: getURLAndPostDataForKeyword() is deprecated` is already marked as resolved, but **I still observe this warning**.

There is a test branch https://github.com/janekptacijarabaci/UXP/tree/pm_url_1 from @janekptacijarabaci that addresses it, but I don't know if it's complete.

**Comment by mattatobin** [comment]
I say we un-depercate it instead

**Comment by JustOff** [comment]
That was my [initial proposition](https://github.com/MoonchildProductions/UXP/issues/121#issuecomment-381331689), which was [declined](https://github.com/MoonchildProductions/UXP/issues/121#issuecomment-381331689) and the deprecation warning is still [present](https://github.com/MoonchildProductions/UXP/blob/eda34d02aa8159def0d811846e9417c37cea15cd/toolkit/components/places/PlacesUtils.jsm#L1225).

**Comment by mattatobin** [comment]
Which ever.. I dunno...

**Comment by janekptacijarabaci** [comment]
> I don't know if it's complete

It should be complete (theoretically) but only a part is tested:
\- plug & play files in the main window of the browser

Also... "openLocation.js" is only for OSX. I cannot test it.

**Comment by mattatobin** [comment]
@janekptacijarabaci No one cares about Machintosh.

**Comment by wolfbeast** [comment]
If there's a problem with Macs, then the people working on those mac builds will have to solve it and propose patches upstream.

**Comment by janekptacijarabaci** [comment]
@wolfbeast @mattatobin @JustOff 
I'm working on `Permission Manager` - https://github.com/MoonchildProductions/UXP/issues/121#issuecomment-381395695 - __5)__

**Comment by wolfbeast** [comment]
Verification of #273 requested.

**Comment by wolfbeast** [comment]
Tearing off tabs has been fixed along the way, apparently. Marked.

**Comment by janekptacijarabaci** [comment]
AFAIK, unchecked:
> Places: Error: ReferenceError: can't access lexical declaration `ContentArea' before initialization
Source File: chrome://browser/content/places/downloadsViewOverlay.xul
Line: 21

was fixed in [diff-0771e8ba6ef02073a2acd52cedcfc93dL1380](https://github.com/MoonchildProductions/UXP/commit/931950a880b3550490422b1855c509be10586858#diff-0771e8ba6ef02073a2acd52cedcfc93dL1380)

**Comment by wolfbeast** [comment]
Means everything in this issues is fixed. closing.
