### ISSUE TITLE
Fix up and enable date/time form input formats/pickers

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1210]
I think the date picker and input check is feature-complete so that can likely be enabled as-is with `dom.forms.datetime`. Note that this will always use the en-US locale but the picker will be clear enough for users to choose something.
Other input formats `dom.forms.datetime.others` that are part of html5 probably need some more work:
- [ ] `<input type=time>` needs some localization work; BZ bugs 1301312 and 1347069, after which the time picker can be enabled with `dom.forms.datetime.timepicker`.
- [ ] `<input type=week>` (BZ 1306216) and `<input type=month>` (BZ 1306215) have acceptance checks but no working implementation behind it yet (NYI by Mozilla)
- [ ] `<input type=datetime-local>` providing a localized version of a date and time input with various formats (BZ 1306217) NYI by Mozilla.

This is a meta issue -- if picking the individual items to work on, please create individual issues for them and link them to this one.
