### ISSUE TITLE
Add missing ES2018 features

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1282]
For full compliance with ES2018, we're still missing a few things.

- [ ] promise.finally(callback)
- [ ] s (dotAll) flag for regexes
- [ ] Regex named capture groups
- [ ] Regex lookbehind
- [ ] Regex unicode property escapes
- [ ] Asynchronous iterators (omg why.)

**Comment by wolfbeast** [comment]
I've done the first three (and ES2020 matchAll) and am quite sick of doing the regex stuff -- someone else can do the other three (named groups, u-prop escapes and async iterators); I'm aware this will take effort so it's flagged for bounties. Have at it! :-)
