### ISSUE TITLE
MailNews Nov/Dec Update Tracking

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1311]
**MailNews**
- [x] 1482248 - don't crash on empty file name in nsMsgLocalStoreUtils::nsShouldIgnoreFile.
- [x] 1509685 - Add more bounds checking in nsMsgDBView::UpdateDisplayMessage() to avoid crashes. 

Unable to reproduce these, perhaps UTF8 regression? (We don't have UTF8)
- [ ] 1000851 - Fix crash of Thunderbird when using a very long username/password. 
- [ ] 1486913 - fix username/password handling in IMAP.
- [ ] 1486913 - fix username/password handling in POP.

**MIME**
- [x] [1571481](https://hg.mozilla.org/comm-central/log?rev=1571481)  - Improve multipart/alternative.

Probably not needed, we don't have UTF8 and already have the sec fix. This was just a follow up.
- [ ] [1463133](https://hg.mozilla.org/comm-central/log?rev=1463133) - Remove unnecessary MIME preludes.  (Missing Partly backed out changeset b39d98d20e6d - Might only be UTF8 so N/A?)

**Comment by mattatobin** [comment]
The UTF8 Related bugs will NOT be ported unless a need arises in the future
