### ISSUE TITLE
Impliment Google WebComponents

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1361]
- [ ] Custom Elements v1
- [ ] Shadow DOM v1
- [ ] HTML Templates
- [ ] ES Modules

**Comment by wolfbeast** [comment]
It is now late May -- I have to know what kind of timeline we're looking at here to decide on how to do releases in the summer. If things are expected to take considerably more time then maybe we need to push WebComponents back to the next milestone and make a redwood-based v29 a thing. I don't want to be hanging on a .9 for a long time, that gives the wrong signals to our users.

@g4jc realistically speaking, what are you looking at in terms of what has been done and what still needs doing to get a basic implementation of WebComponents into UXP? How close are we?

**Comment by g4jc** [comment]
To get minimum working functionality (ignoring devtools work and just getting rendering working), we still need:

**Shadow DOM v1**
- [ ] [Bug 1429656](https://bugzilla.mozilla.org/show_bug.cgi?id=1429656)	Implement ShadowRoot.activeElement
- [ ] [Bug 1430299](https://bugzilla.mozilla.org/show_bug.cgi?id=1430299)	Add DocumentOrShadowRoot 
- [ ] [Bug 1413834](https://bugzilla.mozilla.org/show_bug.cgi?id=1413834)	Implement sequential focus navigation regarding shadow DOM 
- [ ] [Bug 1430303](https://bugzilla.mozilla.org/show_bug.cgi?id=1430303)	Implement ShadowRoot.pointerLockElement
- [ ] [Bug 1430305](https://bugzilla.mozilla.org/show_bug.cgi?id=1430305)	Implement ShadowRoot.fullscreenElement
- [ ] [Bug 1413102](https://bugzilla.mozilla.org/show_bug.cgi?id=1413102)	Ensure Shadow DOM boundaries are dealt properly in event handling
- [ ] [Bug 1438129](https://bugzilla.mozilla.org/show_bug.cgi?id=1438129)	Remove ShadowRoot.applyAuthorStyles.
- [ ] [Bug 1430301](https://bugzilla.mozilla.org/show_bug.cgi?id=1430301)	Implement ShadowRoot.elementFromPoint/elementsFromPoint
- [ ] [Bug 1425864](https://bugzilla.mozilla.org/show_bug.cgi?id=1425864)	Ensure printing documents which have ShadowDOM works
- [ ] [Bug 1066965](https://bugzilla.mozilla.org/show_bug.cgi?id=1066965)	make contentEditable and spellchecking to work in ShadowDOM
- [ ] [Bug 1326028](https://bugzilla.mozilla.org/show_bug.cgi?id=1326028)	customElements.define must upgrade custom element in shadow-including tree order 
- [ ] [Bug 1451037](https://bugzilla.mozilla.org/show_bug.cgi?id=1451037)	check if shadow host has children when fetching before/after pseudos
- [ ] [Bug 1452640](https://bugzilla.mozilla.org/show_bug.cgi?id=1452640)	Implement the functional :host(..) selector. 
- [ ] [Bug 1453789](https://bugzilla.mozilla.org/show_bug.cgi?id=1453789)	Remove Element.createShadowRoot
- [ ] [Bug 1443722](https://bugzilla.mozilla.org/show_bug.cgi?id=1443722)	Implement customElements.upgrade
- [ ] [Bug 1410578](https://bugzilla.mozilla.org/show_bug.cgi?id=1410578)	Make <link rel="stylesheet"> work in shadow trees.
- [ ] [Bug 1331334](https://bugzilla.mozilla.org/show_bug.cgi?id=1331334)	Implement :defined pseudo-class for custom elements
- [ ] [Bug 1500273](https://bugzilla.mozilla.org/show_bug.cgi?id=1500273)	Ensure backward focus navigation works in Shadow DOM.
- [ ] [Bug 1595050](https://bugzilla.mozilla.org/show_bug.cgi?id=1595050)	Update spec comment in CustomElementRegistry::Define to reflect the latest spec
- [ ] [Bug 1552313](https://bugzilla.mozilla.org/show_bug.cgi?id=1552313)	Implement custom element disabledFeatures and disableInternals
- [ ] [Bug 1425685](https://bugzilla.mozilla.org/show_bug.cgi?id=1425685)	Implement HTMLSlotElement.assignedElements
- [ ] [Bug 1518795](https://bugzilla.mozilla.org/show_bug.cgi?id=1518795)	Properly track responsive content in a connected ShadowRoot.

Based on the list above, I feel we're close, but I could certainly use some/any help porting the remaining bugs, and some will not be portable (esp. any code working with CSS).

**Comment by mattatobin** [comment]
Will that get Polymer v2 functioning? That is our goal.

**Comment by wolfbeast** [comment]
> Shadow DOM v1 {list}

Maybe close to getting ShadowDOM in but as stated (and also the opening post here) there are more parts to this than just ShadowDOM, so how close are we to ticking those 4 boxes? Is that something for June/July, or something for October (or later)?

**Comment by g4jc** [comment]
Here's a roadmap/overview of what's been done and where we still need to go to get this working from the DOM and CSS side. Can't speak for the ES Modules as I never worked on them, but we already have some basic functionality that was done long prior to this issue.

**Custom Elements** #1344

CustomElementRegistry.define()
Should already be fully implemented, as it was done by our original fork point.
https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define
Note: Autonomous custom element example does not appear to be working

CustomElementRegistry.get()
Definitely implemented long before fork point
https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/get

CustomElementRegistry.upgrade()
Already implemented and [updated to v1 Spec.](https://github.com/MoonchildProductions/UXP/commit/515c46e695f6cf0a66273e4744330ad7d23fe2cc)
https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/upgrade

CustomElementRegistry.whenDefined()
Already Implemented.
https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined


**HTML**

`<template>`
Already Implemented.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

`<slot>`
Already Implemented.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot

**Methods:**
Note: So far unable to confirm methods are working via tests.

HTMLSlotElement.assignedNodes()
[Implemented](https://github.com/MoonchildProductions/UXP/commit/e31ed5b07466d4a579fe4b025f97c971003fbc3f)
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedNodes

HTMLSlotElement.assignedElements()
[Implemented](https://github.com/MoonchildProductions/UXP/commit/222d316c835019ce64603180e4a73b231b788d76)
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedElements

HTMLSlotElement: slotchange event
[Implemented](https://github.com/MoonchildProductions/UXP/commit/3508e79b1fe7fc928eed2f3c7bf2d628c53fbf17)
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event

**Elements**

Element.attachShadow()
[Implemented.](https://github.com/MoonchildProductions/UXP/commit/873abc7bcb6adc5cbf98ba3e1bd9a3271afc9806)
https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow

Element.shadowRoot()
[Implemented.](https://github.com/MoonchildProductions/UXP/commit/3a74795a56e92313c1b33a54500917794ba09b72)
https://developer.mozilla.org/en-US/docs/Web/API/Element/shadowRoot

Element.part() - FF71+
--Not Implemented.
https://developer.mozilla.org/en-US/docs/Web/API/Element/part
https://bugzilla.mozilla.org/show_bug.cgi?id=1505489 (Servo + XBL removal dependant)

**Node**
Node.isConnected()
Already Implemented.
https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected

Node.getRootNode()
[Implemented](https://github.com/MoonchildProductions/UXP/commit/8797b20746cd80c51cc56225f70ddea6c6b94f9d) via #1585
https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode

**Event**

Event.composed
Already implemented
https://developer.mozilla.org/en-US/docs/Web/API/Event/composed

Event.composedPath
[Implemented.](https://github.com/MoonchildProductions/UXP/commit/7e506bd98dab604062bfe12a44c096eb287721bf)
https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath
Note: Unable to confirm via reftest that this is working.


Slotable.assignedSlot
[Implemented](https://github.com/MoonchildProductions/UXP/commit/3a74795a56e92313c1b33a54500917794ba09b72)
https://developer.mozilla.org/en-US/docs/Web/API/Slotable/assignedSlot
Note: Unable to confirm via reftest that this is working.

**CSS**
:host
--Not Implemented. See #1593 
https://developer.mozilla.org/en-US/docs/Web/CSS/:host()

::slotted()
--Not implemented. See #1592
https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted

::part
--Not Implemented.
https://developer.mozilla.org/en-US/docs/Web/CSS/::part

**DocumentOrShadowRoot**
Basic implementation functional after split. See https://github.com/MoonchildProductions/UXP/commit/43725c7264ca3f63de348d1d1596ce1fe9e64d2d and https://github.com/MoonchildProductions/UXP/commit/bbd59105da97200947ae62b2dc949a1130a40d75.

DocumentOrShadowRoot.activeElement
[Implemented](https://github.com/MoonchildProductions/UXP/pull/1591).
https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement

--Not Implemented:
https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/elementFromPoint
https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/elementsFromPoint
https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/fullscreenElement
https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/getSelection
https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/pointerLockElement
https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/styleSheets

**Comment by wolfbeast** [comment]
Signing off on ES modules. That part should now be complete.

**Comment by g4jc** [comment]
Great news! That just leave us with CSS, Element.part, additional DocumentOrShadowRoot elements, and flipping the W3C Pointer events pref (#1630). CSS is the full stop road blocker at the moment, and my attempts to get any communication from people that wrote the code have fell flat.
