### ISSUE TITLE
Investigate the possibility to de-e10s of Add-on SDK (Jetpack)

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#331]
Previously we were able to successfully get rid of the e10s-related bs in the following modules:

- [ ] `sdk/tabs` - [PM27#785](https://github.com/MoonchildProductions/Pale-Moon/pull/785)
- [ ] `sdk/context-menu` - [PM27#784](https://github.com/MoonchildProductions/Pale-Moon/pull/784)
- [ ] `sdk/context-menu@2` - [PM27#787](https://github.com/MoonchildProductions/Pale-Moon/pull/787)

Unfortunately, this is not so easy on UXP and requires further investigation.

Separated from #120, since it's not a release blocker.
