### ISSUE TITLE
Port Pale Moon to UXP

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#57]
This is the Meta bug for porting `Pale Moon` to `UXP`.

----

- [x] Make `Pale Moon` Build
    - [x] Basic `moz.build` changes
    - [x] Basic `c++` changes
- [x] Changes to front-end code to account for back-end changes
    - [x] Initial loading of browser window
    - [x] Developer Tools (Issue #102)
    - [x] Fullscreen (Issue #270) - _No longer blocking unstable_
    - [x] Findbar
    - [x] Places (History, Bookmarks, and Downloads)
      - [x] Library Window
      - [x] Downloads Panel
      - [x] Boomarks Sidebar
      - [x] History Sidebar
    - [x] Preferences Window - _Does not block unstable_
    - [x] Doorhangers
        - [x] Odd checkbox element present
    - [x] Sync - _Does not block unstable_
    - [x] Login/Password Manager
    - [x] New Tab Page (about:newtab) - _Does not block unstable_
    - [x] Shell Service
    - [x] URL bar
    - [x] Session Store
    - [x] Feeds Service
    - [x] **_More as they are determined_**
- [ ] Add-ons
    - [x] Extensions
      - [x] Bootstrap
      - [x] Jetpack (Issue #120)
    - [x] Default Theme - _No longer blocking unstable_
    - [ ] Language Packs - _Does not block unstable_
- [x] Packaging
    - [x] `package-manifest.in` / `removed-files.in`
    - [x] Windows Installer
- [x] Default Preferences Audit - _Does not block unstable_
    - [x] Application Preferences
    - [x] Branding Preferences

**Comment by wolfbeast** [comment]
Sync has been fixed, ticked it off.

**Comment by wolfbeast** [comment]
Ticked off several more things that are fixed. Almost there ;)

**Comment by wolfbeast** [comment]
Everything but the language packs is addressed -- closing.

**Comment by JustOff** [comment]
In fact, language packs are almost ready, but we need to freeze the tree against string changes so that the translation can be finalized before the release.

@wolfbeast, please don't forget to create a corresponding task in [pale-moon-localization](https://github.com/MoonchildProductions/pale-moon-localization) when you decide that the time has come.

**Comment by JustOff** [comment]
Roger that.
