### ISSUE TITLE
Implement module type scripting

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#618]
Spun off from #200 as a tracking bug for implementation, to follow Mozilla's progress chronologically for `<script type="module">` landed preffed in Firefox 54 and enabled by default in Firefox 60.

- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1340865 FF54 (merged)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1330682 FF54 (Janek) (merged)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1330900 FF55 (merged)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1362119 FF55 (re-arch) #1603 (merged)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1358882 FF57 (merged)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1362098 FF57 (merged)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1388728 FF57 (merged)
    - [x] Remove eager instantiation ([Bug 1295978](https://bugzilla.mozilla.org/show_bug.cgi?id=1295978))  (merged)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1374239 FF57 (merged)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1394492 FF57 (merged)
- [x] ~https://bugzilla.mozilla.org/show_bug.cgi?id=1391584 FF57~ (test adjustment only, N/A)
- [x] ~https://bugzilla.mozilla.org/show_bug.cgi?id=1371551 FF59~
    N/A since this is to make WEs work with module imports (special-case WEs). We are spec compliant for URLs otherwise.
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1420412 FF59 171124
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1420420 FF59 171207
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1372258 FF59 171208
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1365187 FF59 171215
- [x] ~https://bugzilla.mozilla.org/show_bug.cgi?id=1330688 FF59 171220~ (error messaging post-refactor)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1393429 Fix test failures meta (resolves spec issues).
    - [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1421259 FF59 171202
    - [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1425145 FF59 171221
    - [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1425843 FF59 171220
    - [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1425885 FF59 171220
    - [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1426140 FF59 180103
    - [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1426189 FF59 (document.currentScript) 180108
    - [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1426190 FF59 (integrity=) 171221
    - [x] ~https://bugzilla.mozilla.org/show_bug.cgi?id=1426675 FF59 180104~ (wpt update only, N/A)
    - [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1426440 FF59 180103
    - [x] ~https://bugzilla.mozilla.org/show_bug.cgi?id=1426642 FF59 (in-xhtml) 180104~ (wpt update only, N/A)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1361369 FF59 180108
- [x] ~https://bugzilla.mozilla.org/show_bug.cgi?id=1428002 FF59~ (flip on-> nightly)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1382020 FF60 (stop redundant pre-fetch, optmization)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1342416 FF60 (preloading, optimization)
- [x] ~https://bugzilla.mozilla.org/show_bug.cgi?id=1438139 FF60~ (flip on)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1453559 FF61
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1461751 FF62 (see #1624)
- [x] ~https://bugzilla.mozilla.org/show_bug.cgi?id=1496159 FF63~ (bytecode cache, N/A)
- [x] ~https://bugzilla.mozilla.org/show_bug.cgi?id=1485698 FF63~ (JIT meta import, N/A)
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1529203 FF66

**Comment by wolfbeast** [comment]
I'll be having another look at this soon, but for the moment our current implementation seems to at least solve the web compat issues people have reported (e.g. Chrome's issue tracker - monorail). It's probably OK to merge the current state and run it enabled on the unstable to see if people report more issue with it, and if not, to enable it on release while in-progress.

**Comment by mattatobin** [comment]
Blocks #1361

**Comment by wolfbeast** [comment]
With the current set of changes (especially the removal of eager instantiation) it seems we've gained a nice performance win here on sites heavily using modules (e.g. Github).

**Comment by wolfbeast** [comment]
> Are there any live websites/reftests I should test against?

The average collection of websites that are likely to use these technologies? I don't know which frameworks use ES modules or what not. I've just spot-tested these changes.

**Comment by win7-7** [comment]
With latest unstable:

https://bugs.chromium.org/p/chromium/issues/list

Error: No such property on self-hosted object: "ModuleDeclarationInstantiation"

Chromium website worked before recent ES6 modules changes.

ModuleObject.cpp:

JS_SELF_HOSTED_FN("declarationInstantiation", "ModuleDeclarationInstantiation", 0, 0),
JS_SELF_HOSTED_FN("evaluation", "ModuleEvaluation", 0, 0),

Mozilla removed these so same should be done.

Also there is typo:

Module.js: 

Line 507:

return callFunction(CallModuleMethodIfWrapped, this, "ModuleEvaluatie");

**Comment by wolfbeast** [comment]
Yeah I forgot to remove the old function declarations there.
Thanks for spotting the typo! Patch incoming.

**Comment by wolfbeast** [comment]
This issue has now been fully resolved. We should have a fully spec-compliant and 100% working implementation of ES modules at this point.
Any potential progblems or regressions should be opened as new issues.
