### ISSUE TITLE
Officially release Pale Moon for macOS

### ISSUE THREAD

**Issue by SpockFan02** [MoonchildProductions/UXP#689]
Pale Moon for macOS is planned to become official. This is a meta-issue for Mac-specific problems and to track what needs to be done/fixed. If anything Mac-specific needs to be fixed before the official release, please mention it here.

OS X 10.7 and higher will be supported.

- [ ] Functionality and UX
  - [X] Application menu missing items [was fixed in 27.6.2](https://forum.palemoon.org/viewtopic.php?f=41&t=17609)
  - [ ] Intermittent window-dragging problems, possibly theme-dependent, unsure if still present with UXP ([Pale-Moon issue #1598](https://github.com/MoonchildProductions/Pale-Moon/issues/1598))
  - [ ] Restarting creates a duplicate icon on the dock if the application has been placed there [Not blocking release]

Pale Moon on macOS functions and is usable and stable.

- [ ] Theme
  - [ ] Decide whether or not to revert to old osx theme
  - [X] Lightweight themes (personas)
    - [X] Make sure personas don't kill the titlebar and caption buttons (#491)
    - [ ] Missing window title [Not blocking release]
  - [X] Private Browsing windows
    - [X] Make sure Private Browsing windows have caption buttons (#584)
    - [X] Make sure [Private Browsing mode is indicated to the user](https://bugzilla.mozilla.org/show_bug.cgi?id=749394)
      - [X] about:privatebrowsing
      - [X] Purple mask indicator (#553)
      - [ ] Darker window color [Not blocking release]
    - [ ] Missing window title [Not blocking release]
  - [X] Ensure expected placement of caption buttons (#586)
  - [ ] Bookmark doorhangers and Properties dropdowns missing button icons [Not blocking release]
  - [ ] Unexpected expansion/collapse behavior in bookmark doorhangers

Lightweight theme and Private Browsing issues had significant impact on functionality and user experience, but have been resolved, and other problems are minor.

- [ ] Release engineering
  - [X] Building and packaging works as expected (There have been issues, e.g. #573)
  - [ ] Decide proper configuration for official builds and who will produce them, and provide access to distribution infrastructure (http://mac.palemoon.org/dist/)
  - [ ] Enable updating and make sure it works

This will require testing.

- [ ] Documentation
  - [ ] Update [wiki page](https://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/macOS), provide sample mozconfig, etc.
  - [ ] Link to build instructions ([Pale-Moon PR #1417](https://github.com/MoonchildProductions/Pale-Moon/pull/1417))
  - [ ] mac.palemoon.org?
  - [ ] Update information
    - [ ] Project homepage
    - [ ] Roadmap
    - [ ] Screenshots?
    - [ ] Pale Moon for Mac OSX forum board
    - [ ] etc.

**Comment by asimperson** [comment]
- The Private Browsing window's minimize/maximize/close buttons are not themed correctly and in the wrong order for Mac.

<img width="292" alt="private_browsing" src="https://user-images.githubusercontent.com/6888097/44690500-ed768900-aa0f-11e8-9c06-c2e4ba3a2dd6.png">

**Comment by SpockFan02** [comment]
Thanks for reporting. From your screenshot, it does not look like you're using the default theme, and in Private Browsing windows and/or when a lightweight theme is installed, the styling of the titlebar and caption buttons (close/minimize/maximize or fullscreen) is theme-dependent. In Pale Moon 28.0.0 with the default theme, is the problem still present? If not, the issue lies with the particular theme you're using.

**Comment by asimperson** [comment]
I tried again with the default theme. When the window is first created, the icons do not appear and there is no title bar. However, if I click in the correct spots they do close/minimize/full screen the window. If I full screen the window and then change it back, the icons and title do appear. 
<img width="258" alt="private_browsing_default_theme" src="https://user-images.githubusercontent.com/6888097/44748052-9cc06800-aac3-11e8-9cef-8caf68123504.png">
This screenshot shows three windows. The top left is a normal window. The 2nd is a private browsing window that has been full screened and then changed back. The 3rd is a private browsing window as it appears when a new one is opened.

**Comment by SpockFan02** [comment]
I'm afraid I cannot confirm this (caption buttons appear in Private Browsing windows and entering and leaving fullscreen does not change this). Have you tried with a different profile? It could be caused by an add-on or userChrome. It would also be good to know which version of macOS you're using, and what build of Pale Moon.

**Comment by g4jc** [comment]
Not a MacOSX user myself, but I believe this modal dialog issue affects Mojave users since we have the same deadcode as work-around for old GCC. 

Might be worth someone testing it out -> https://hg.mozilla.org/mozilla-central/rev/3920c858319d

**Comment by trav90** [comment]
@SpockFan02 @wicknix quick question: Are/will 32-bit Mac's be supported? Or is OS X 10.7 and higher 64-bit only?

**Comment by wicknix** [comment]
@g4jc  Thanks will give that a look.
@trav90  MacOS had 32-bit support with the early 2006 and older core duo machines. 10.7 and up are all 64-bit starting with the core 2 duo machines released in late 2006 IIRC. PM27 *could* be built for 32-bit, but PM28 won't build or run on anything older than 10.7. So to make a long story short... there will be no 32-bit support on MacOS.

**Comment by trav90** [comment]
Thanks! Reason I asked is there is some 32-bit specific Mac code in media that either needed updated or removed. Now I know what to do with it!

**Comment by asimperson** [comment]
The UI appears to be a different color on Mojave vs. High Sierra. These screenshots are with the Littlemoon theme, but the issue is the same with the default theme, so I don't think it's a theming issue. Switching to Dark Mode doesn't change anything. So far I haven't seen any other apps with this issue either. 

High Sierra:
<img width="298" alt="palemoon281-highsierra" src="https://user-images.githubusercontent.com/6888097/46790153-179bb600-ccf3-11e8-8454-ddc8e6e8b9a3.png">

Mojave:
<img width="347" alt="screen shot 2018-10-11 at 1 04 13 am" src="https://user-images.githubusercontent.com/6888097/46790133-0c488a80-ccf3-11e8-899a-7cbe6efbc966.png">

**Comment by wicknix** [comment]
@asimperson Try this build. Built with 10.9sdk. If it still has the light colors i'll try with 10.11.
https://drive.google.com/file/d/1h90XAyly8X3xR9S9ObqBC_ur0HfXGnq5/view?usp=sharing

**Comment by asimperson** [comment]
@wicknix No effect, unfortunately.

**Comment by wolfbeast** [comment]
We've decided to, for the time being, disallow lightweight themes so this is not a blocker anymore.

**Comment by wolfbeast** [comment]
Since wicknix has decided to divert his attentions and priorities elsewhere and ragequitting when reminded of his promises, we are now once again without a Mac person. Putting this on hold.
