### ISSUE TITLE
Remove FxA completely

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#812]
The only entity that can reasonably run Firefox Accounts (FxA) is Mozilla, due to its complexity required server-side.
Considering that fact and the fact that they are tightening up all their service use for non-MozCo clients, it's likely only going to be a matter of time before non-MozCo clients are going to be stopped at the door. In addition this service is at the whim of arbitrary changes to cater to Firefox browser changes.

Conversely, Sync 1.1 (Weave) is an open system that can, has been and is being implemented in custom installations everywhere (FSyncMS, OwnCloud, etc.).

Add to that the fact that FxA is less secure than Weave in terms of safeguarding encryption keys and keeping entropy sources private.

This can simplify UXP's Sync client considerably and make it a single synchronization client for all applications without unnecessary complexity and bugs.

We should coordinate with others (e.g. Hyperbola) to make this change work for them.

- [x] Phase 1: Revert UXP Sync client to Tycho level (known-good weave 1.1 without hacks to dodge FxA assumptions). ~~This should also solve #728 as a bonus.~~
- [x] Phase 1: Remove FxA considerations completely from Sync client, making it always use Weave
- [x] Phase 1: Change Basilisk front-end to use Weave
- [x] Phase 2a: Remove CloudSync
- [x] Phase 2b: Replace Basilisk's FxA-infected FE code
  - [x] Remove FxA Sync
  - [x] Port Pale Moon Sync FE Client
  - [x] History menu item and about:sync-tabs (Tabs from Other Devices [Synced Tabs])
  - [x] Tools menu items (Set Up Sync and Sync Now)
  - [x] Port Pale Moon Sync `toolbarbutton` and create one for Synced Tabs (Tabs from Other Devices)
  - [x] Final Validation
  - [x] Cleanup (does not block)
- [x] Phase 2c: remove FxA authenticator modules
- [x] Phase 2d: remove FxA front-end resources

**Comment by wolfbeast** [comment]
Since #728 turned out to be a wild goose chase caused by FSyncMS stripping the port, this can move forward finally.

**Comment by wolfbeast** [comment]
Landing this in 2 phases: phase 1 to make Weave (sync 1.1) be used by applications, and phase 2 to clean up the dead code and resources.

**Comment by JustOff** [comment]
It seems that #898 broke the context menu in Basilisk:

```
TypeError: Weave.Service.clientsEngine.remoteClients is undefined   browser-fxaccounts.js:85:5
	get remoteClients chrome://browser/content/browser-fxaccounts.js:85:5
	initPageContextMenu chrome://browser/content/browser-fxaccounts.js:367:11
	initSyncItems chrome://browser/content/nsContextMenu.js:542:5
	CM_initItems chrome://browser/content/nsContextMenu.js:114:5
	CM_initMenu chrome://browser/content/nsContextMenu.js:85:5
	nsContextMenu chrome://browser/content/nsContextMenu.js:21:3
	onpopupshowing chrome://browser/content/browser.xul:1:119

TypeError: gContextMenu is null  browser.xul:1:1
	oncommand chrome://browser/content/browser.xul:1:1
```

**Comment by g4jc** [comment]
Confirming. Affects Iceweasel-UXP as well (without any backported application changes yet). It's due to [application/basilisk/base/content/browser-fxaccounts.js](http://xref.palemoon.org/uxp-trunk/search?string=Weave.Service.clientsEngine.remoteClients&find=&findi=&filter=%5E%5B%5E%5C0%5D*%24&hitlimit=&tree=uxp-trunk) calling [Weave.Service.clientsEngine.remoteClients](https://hg.mozilla.org/mozilla-central/rev/3db372da6fe1).
The function is not declared because it existed in [services/sync/modules/telemetry.js](https://hg.mozilla.org/mozilla-central/diff/a4566b20e0cc/services/sync/modules/telemetry.js#l1.50) which was removed in this commit: https://github.com/MoonchildProductions/UXP/commit/0c47c83e1b3b7d95681a43fbb0de0e17b2cd5b25#diff-637e329f95f8c363fae6e03feee0c128

The function will have to be stubbed into the browser-fxaccounts.js file without telemetry and/or removed completely to avoid the error.

**Comment by wolfbeast** [comment]
For what little sense it makes to have that in a -telemetry- module, I don't know.
In any case "send tab to" with a targeted device is something unique to FxA, so removal was warranted. I left the init and update functions as stubs because I don't want to dig into the code to find all the callers right this instant, but do want to fix the context menu.

**Comment by wolfbeast** [comment]
Basilisk's UI panel is fragile and has deep integration with the fxa/sync combo. First attempt at removing this failed miserably - looks like the FE integration stuff in Basilisk is best left as untouched as possible or CUI will break.

**Comment by wolfbeast** [comment]
Co-assigning @mattatobin to deal with PanelUI stuff.

**Comment by mattatobin** [comment]
CUI is evil. I plan to exterminate sync from Basilisk then port over the Pale Moon version of the code.

I will turn the standard sync toolbar button into a split button with setup/sync now and open the about page for tabs from other devices and an item for preferences.

I shall make this optional at build time and I want to do this in a way that uses an init jsm and overlays so that we can possibly make the sync ui common to any browser application.

This would allow for deduplication and consistancy in funtionality and future changes.

I will be backporting the toolbar button enhancements back to Pale Moon regardless of it potentally becoming shared code.

**Comment by wolfbeast** [comment]
Everything should be done. Closing.
