### ISSUE TITLE
Remove WebExtension support

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#936]
Since we can't hope to focus if we spread too thin, let alone offer something uniform if we're not keeping parity with mainstream, WebExtension support should be removed from UXP. Our platform will focus more tightly on everything XUL, including extension technologies which are effectively now our own after Mozilla abandoned it.

This is a meta issue to remove it from all components.

Please create separate issues for individual components and make them block this meta bug.

Plan of action:
- [x] Disable Web Extensions in Basilisk short term
- [x] Remove Web Extension support in the Basilisk application
- [x] Remove Web Extension support in the platform interface code, including any specific WE APIs
- [x] Remove the Web Extension add-ons manager (WebExAM)

@mattatobin assigning you to this since you probably have the best grasp on how to give this shape.
(P.S.: I hold you to your promise to never complain about Jetpack again when WE support is removed ;) )

**Comment by wolfbeast** [comment]
I'll start taking out `MOZ_WEBEXTENSIONS` conditional code.

**Comment by wolfbeast** [comment]
Aside from the potential of integration code that's now dead still sitting in our tree, this should be completed now.
