### ISSUE TITLE
Remove e10s code

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#953]
This is a meta issue for the large task of removing unnecessary multi-process complexity from our tree.
This will be a massive task and take a lot of time, so this issue will be the master tracking issue for this effort, keeping a checklist of what needs to be done - this checklist will grow as time goes on. 

- [ ] Remove CPOWs
- [ ] Remove e10s in other code
  - [ ] Front-end
    - [ ] Remove e10s code from Pale Moon
    - [ ] Remove e10s code from Basilisk
  - [ ] DOM
  - [ ]  Embedding code
    - [ ] Revert `nsWebBrowserPersist` to a non-e10s state
  - [ ] Toolkit
  - [ ] Cache
  - [ ] Rendering/layout
- [ ] Remove IPC and its use (except for the original OOPP implementation)

**Comment by wolfbeast** [comment]
Research into the IPC protocol has indicated that e10s parent/Child structures are advantageous even for single-process use because it works into the favor of multithreading. So for this issue we need to focus on dealing with primarily the message manager and actual cross-process/remote tasking.
